# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/pgrimes/miniforge3/envs/pypo_pec/bin/cmake

# The command to remove a file.
RM = /home/pgrimes/miniforge3/envs/pypo_pec/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pgrimes/github/PyPO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pgrimes/github/PyPO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/pgrimes/miniforge3/envs/pypo_pec/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/pgrimes/miniforge3/envs/pypo_pec/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pgrimes/github/PyPO/CMakeFiles /home/pgrimes/github/PyPO//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pgrimes/github/PyPO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pyporefl

# Build rule for target.
pyporefl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pyporefl
.PHONY : pyporefl

# fast build rule for target.
pyporefl/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyporefl.dir/build.make CMakeFiles/pyporefl.dir/build
.PHONY : pyporefl/fast

#=============================================================================
# Target rules for targets named pypobeam

# Build rule for target.
pypobeam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pypobeam
.PHONY : pypobeam

# fast build rule for target.
pypobeam/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypobeam.dir/build.make CMakeFiles/pypobeam.dir/build
.PHONY : pypobeam/fast

#=============================================================================
# Target rules for targets named pypotransf

# Build rule for target.
pypotransf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pypotransf
.PHONY : pypotransf

# fast build rule for target.
pypotransf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypotransf.dir/build.make CMakeFiles/pypotransf.dir/build
.PHONY : pypotransf/fast

#=============================================================================
# Target rules for targets named pypocpu

# Build rule for target.
pypocpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pypocpu
.PHONY : pypocpu

# fast build rule for target.
pypocpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypocpu.dir/build.make CMakeFiles/pypocpu.dir/build
.PHONY : pypocpu/fast

#=============================================================================
# Target rules for targets named pypogpu

# Build rule for target.
pypogpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pypogpu
.PHONY : pypogpu

# fast build rule for target.
pypogpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypogpu.dir/build.make CMakeFiles/pypogpu.dir/build
.PHONY : pypogpu/fast

src/CPU/InterfaceCPU.o: src/CPU/InterfaceCPU.cpp.o
.PHONY : src/CPU/InterfaceCPU.o

# target to build an object file
src/CPU/InterfaceCPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypocpu.dir/build.make CMakeFiles/pypocpu.dir/src/CPU/InterfaceCPU.cpp.o
.PHONY : src/CPU/InterfaceCPU.cpp.o

src/CPU/InterfaceCPU.i: src/CPU/InterfaceCPU.cpp.i
.PHONY : src/CPU/InterfaceCPU.i

# target to preprocess a source file
src/CPU/InterfaceCPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypocpu.dir/build.make CMakeFiles/pypocpu.dir/src/CPU/InterfaceCPU.cpp.i
.PHONY : src/CPU/InterfaceCPU.cpp.i

src/CPU/InterfaceCPU.s: src/CPU/InterfaceCPU.cpp.s
.PHONY : src/CPU/InterfaceCPU.s

# target to generate assembly for a file
src/CPU/InterfaceCPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypocpu.dir/build.make CMakeFiles/pypocpu.dir/src/CPU/InterfaceCPU.cpp.s
.PHONY : src/CPU/InterfaceCPU.cpp.s

src/CUDA/KernelsRTf.o: src/CUDA/KernelsRTf.cu.o
.PHONY : src/CUDA/KernelsRTf.o

# target to build an object file
src/CUDA/KernelsRTf.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypogpu.dir/build.make CMakeFiles/pypogpu.dir/src/CUDA/KernelsRTf.cu.o
.PHONY : src/CUDA/KernelsRTf.cu.o

src/CUDA/KernelsRTf.i: src/CUDA/KernelsRTf.cu.i
.PHONY : src/CUDA/KernelsRTf.i

# target to preprocess a source file
src/CUDA/KernelsRTf.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypogpu.dir/build.make CMakeFiles/pypogpu.dir/src/CUDA/KernelsRTf.cu.i
.PHONY : src/CUDA/KernelsRTf.cu.i

src/CUDA/KernelsRTf.s: src/CUDA/KernelsRTf.cu.s
.PHONY : src/CUDA/KernelsRTf.s

# target to generate assembly for a file
src/CUDA/KernelsRTf.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypogpu.dir/build.make CMakeFiles/pypogpu.dir/src/CUDA/KernelsRTf.cu.s
.PHONY : src/CUDA/KernelsRTf.cu.s

src/CUDA/Kernelsf.o: src/CUDA/Kernelsf.cu.o
.PHONY : src/CUDA/Kernelsf.o

# target to build an object file
src/CUDA/Kernelsf.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypogpu.dir/build.make CMakeFiles/pypogpu.dir/src/CUDA/Kernelsf.cu.o
.PHONY : src/CUDA/Kernelsf.cu.o

src/CUDA/Kernelsf.i: src/CUDA/Kernelsf.cu.i
.PHONY : src/CUDA/Kernelsf.i

# target to preprocess a source file
src/CUDA/Kernelsf.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypogpu.dir/build.make CMakeFiles/pypogpu.dir/src/CUDA/Kernelsf.cu.i
.PHONY : src/CUDA/Kernelsf.cu.i

src/CUDA/Kernelsf.s: src/CUDA/Kernelsf.cu.s
.PHONY : src/CUDA/Kernelsf.s

# target to generate assembly for a file
src/CUDA/Kernelsf.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypogpu.dir/build.make CMakeFiles/pypogpu.dir/src/CUDA/Kernelsf.cu.s
.PHONY : src/CUDA/Kernelsf.cu.s

src/common/InterfaceBeam.o: src/common/InterfaceBeam.cpp.o
.PHONY : src/common/InterfaceBeam.o

# target to build an object file
src/common/InterfaceBeam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypobeam.dir/build.make CMakeFiles/pypobeam.dir/src/common/InterfaceBeam.cpp.o
.PHONY : src/common/InterfaceBeam.cpp.o

src/common/InterfaceBeam.i: src/common/InterfaceBeam.cpp.i
.PHONY : src/common/InterfaceBeam.i

# target to preprocess a source file
src/common/InterfaceBeam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypobeam.dir/build.make CMakeFiles/pypobeam.dir/src/common/InterfaceBeam.cpp.i
.PHONY : src/common/InterfaceBeam.cpp.i

src/common/InterfaceBeam.s: src/common/InterfaceBeam.cpp.s
.PHONY : src/common/InterfaceBeam.s

# target to generate assembly for a file
src/common/InterfaceBeam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypobeam.dir/build.make CMakeFiles/pypobeam.dir/src/common/InterfaceBeam.cpp.s
.PHONY : src/common/InterfaceBeam.cpp.s

src/common/InterfaceReflector.o: src/common/InterfaceReflector.cpp.o
.PHONY : src/common/InterfaceReflector.o

# target to build an object file
src/common/InterfaceReflector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyporefl.dir/build.make CMakeFiles/pyporefl.dir/src/common/InterfaceReflector.cpp.o
.PHONY : src/common/InterfaceReflector.cpp.o

src/common/InterfaceReflector.i: src/common/InterfaceReflector.cpp.i
.PHONY : src/common/InterfaceReflector.i

# target to preprocess a source file
src/common/InterfaceReflector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyporefl.dir/build.make CMakeFiles/pyporefl.dir/src/common/InterfaceReflector.cpp.i
.PHONY : src/common/InterfaceReflector.cpp.i

src/common/InterfaceReflector.s: src/common/InterfaceReflector.cpp.s
.PHONY : src/common/InterfaceReflector.s

# target to generate assembly for a file
src/common/InterfaceReflector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pyporefl.dir/build.make CMakeFiles/pyporefl.dir/src/common/InterfaceReflector.cpp.s
.PHONY : src/common/InterfaceReflector.cpp.s

src/common/Transform.o: src/common/Transform.cpp.o
.PHONY : src/common/Transform.o

# target to build an object file
src/common/Transform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypotransf.dir/build.make CMakeFiles/pypotransf.dir/src/common/Transform.cpp.o
.PHONY : src/common/Transform.cpp.o

src/common/Transform.i: src/common/Transform.cpp.i
.PHONY : src/common/Transform.i

# target to preprocess a source file
src/common/Transform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypotransf.dir/build.make CMakeFiles/pypotransf.dir/src/common/Transform.cpp.i
.PHONY : src/common/Transform.cpp.i

src/common/Transform.s: src/common/Transform.cpp.s
.PHONY : src/common/Transform.s

# target to generate assembly for a file
src/common/Transform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pypotransf.dir/build.make CMakeFiles/pypotransf.dir/src/common/Transform.cpp.s
.PHONY : src/common/Transform.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pypobeam"
	@echo "... pypocpu"
	@echo "... pypogpu"
	@echo "... pyporefl"
	@echo "... pypotransf"
	@echo "... src/CPU/InterfaceCPU.o"
	@echo "... src/CPU/InterfaceCPU.i"
	@echo "... src/CPU/InterfaceCPU.s"
	@echo "... src/CUDA/KernelsRTf.o"
	@echo "... src/CUDA/KernelsRTf.i"
	@echo "... src/CUDA/KernelsRTf.s"
	@echo "... src/CUDA/Kernelsf.o"
	@echo "... src/CUDA/Kernelsf.i"
	@echo "... src/CUDA/Kernelsf.s"
	@echo "... src/common/InterfaceBeam.o"
	@echo "... src/common/InterfaceBeam.i"
	@echo "... src/common/InterfaceBeam.s"
	@echo "... src/common/InterfaceReflector.o"
	@echo "... src/common/InterfaceReflector.i"
	@echo "... src/common/InterfaceReflector.s"
	@echo "... src/common/Transform.o"
	@echo "... src/common/Transform.i"
	@echo "... src/common/Transform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

